### ISSUE TITLE
It didn't work when the working directory contains whitespace

### ISSUE THREAD

**Issue by jiamingz42** [ddrscott/vim-side-search#7] opened 2018-07-11 03:36 UTC
It didn't work when the working directory contains whitespace

**Comment by ddrscott** [comment] 2018-07-11 13:11
Work on OSX.
![whitespace-bug](https://user-images.githubusercontent.com/1975119/42573467-c7c96748-84e1-11e8-8baf-6b3f90be5e21.gif)

Are you in Windows? (I don't have a Windows for testing)
Also, does Silver Searcher work on your system?

**Comment by jiamingz42** [comment] 2018-07-11 16:02
My OS is MacOS High Sierra. `ag` is installed and its version is 2.1.0

I open vim in directory `~/Foo Bar`. I saw the following error messages 

```
ERR: Error stat()ing: /Users/xyz/Foo
ERR: Error opening directory /Users/xyz/Foo: No such file or d
ERR: Error stat()ing: Bar
ERR: Error opening directory Bar: No such file or directory
```

The plugin work fine when I change directory from `Foo Bar` to `FooBar`.

Here is what I put in `~/.vimrc`

````
" How should we execute the search?
" --heading and --stats are required!
let g:side_search_prg = 'ag --word-regexp'
  \. " --ignore='*.js.map'"
  \. " --heading --stats -B 1 -A 4"

" Can use `vnew` or `new`
let g:side_search_splitter = 'vnew'

" I like 40% splits, change it if you don't
let g:side_search_split_pct = 0.4
```

**Comment by ddrscott** [comment] 2018-07-11 20:50
Tried your same `.vimrc` settings, but still can't reproduce the error.

The plugin doesn't `stat` any files when Vim starts up, so I'm guessing it could be a different plugin still in your `.vimrc`.

**Comment by ddrscott** [comment] 2019-10-02 13:54
Closing since I can't reproduce and it's been a looooooong time.

**Closed as completed by ddrscott** 2019-10-02 13:54 UTC
